#
#   ubuntu/Ubuntu-Initialize.yaml
#
#   David Janes
#   Consensas
#   2018-12-22
#

- name: Ubuntu Initialize
  hosts: "{{ in_hosts }}"
  become: true
  become_user: root

  tasks:
  - name: Ping
    ping:

  - name: Install Standard Packages
    become: yes
    apt:
      pkg:
      - curl
      - net-tools

  - name: "change hostname to '{{ inventory_hostname }}'"
    hostname:
      name: "{{ inventory_hostname }}"
