#
#   ansible/Kubernetes-Common.sh
#
#   David Janes
#   Consensas
#   2018-12-23
#

- name: Kubernetes Common Setup
  hosts: "{{ in_hosts }}"
  become_user: root
  become: true

  tasks:
  - name: Ping
    ping:

  - name: Make /etc/consensas.ansible
    become: yes
    file:
      path: /etc/consensas.ansible
      state: directory

#
#   /etc/sysctl.d/99-kubernetes-cri.conf
#
  - name: Networking net.bridge.bridge-nf-call-iptables
    become: yes
    register: sysctl1
    lineinfile:
      create: yes
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      regexp: "^net.bridge.bridge-nf-call-iptables"
      line: "net.bridge.bridge-nf-call-iptables  = 1"

  - name: Networking net.ipv4.ip_forward
    become: yes
    register: sysctl2
    lineinfile:
      create: yes
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      regexp: "^net.ipv4.ip_forward"
      line: "net.ipv4.ip_forward = 1"

  - name: Networking net.bridge.bridge-nf-call-ip6tables
    become: yes
    register: sysctl3
    lineinfile:
      create: yes
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      regexp: "^net.bridge.bridge-nf-call-ip6tables"
      line: "net.bridge.bridge-nf-call-ip6tables = 1"

  - name: Load /etc/sysctl.d
    become: yes
    when: sysctl1.changed or sysctl2.changed or sysctl3.changed
    shell: "sysctl --system"

#
#   /etc/modules
#
  - name: /etc/modules (overlay)
    become: yes
    register: modules1
    lineinfile:
      create: yes
      path: /etc/modules
      regexp: "^overlay$"
      line: "overlay"

  - name: /etc/modules (br_netfilter)
    register: modules2
    become: yes
    lineinfile:
      create: yes
      path: /etc/modules
      regexp: "^br_netfilter$"
      line: "br_netfilter"

  - name: /etc/modules changed - reboot 
    become: yes
    when: modules1.changed or modules2.changed
    reboot:

#
#   Swap
#
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

#
#   Docker
#
  - name: Install Docker Prereqs
    become: yes
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Add Docker Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg 
      state: present

  - name: Add Docker Repository
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"

  - name: Install Docker/containerd
    become: yes
    register: docker
    apt:
      pkg:
      - containerd.io

  - pause:
      seconds: 5

  - name: Create /etc/containerd
    become: yes
    file:
      path: /etc/containerd
      state: directory
      mode: '0755'

  - name: Test /etc/consensas.ansible/containerd_config
    become: yes
    register: containerd_config
    stat:
      path: /etc/consensas.ansible/containerd_config

  - name: Make /etc/containerd/config.toml
    become: yes
    when: containerd_config.stat.exists == false
    shell: "containerd config default > /etc/containerd/config.toml"

  - name: Make /etc/consensas.ansible/containerd_config
    become: yes
    when: containerd_config.stat.exists == false
    file:
      path: /etc/consensas.ansible/containerd_config
      state: touch

  - pause:
      seconds: 5

  - name: Restart containerd 
    become: yes
    when: containerd_config.stat.exists == false
    systemd:
      state: restarted
      name: containerd

#
#   Kubernetes
#

  - name: Add K8S Key
    become: yes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add K8S Repository
    become: yes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install kubeadm
    become: yes
    register: kubeadm
    apt:
      pkg:
      - kubeadm
